Coding challenge
apertium/apertium-kaa pull request #3
Opened 2019-04-23 19:42 UTC by sharapat

changed o'->ó, a'->á, u'->ú, g'->ǵ, n'->ń and ts->c, sh->ch where necessary

2019-04-24 20:27 UTC, IlnarSelimcan commented
## Coverage on the [story](https://github.com/taruen/apertiumpp/blob/master/data4apertium/corpora/jam/kaa.txt) before @sharapat 's changes:

```
apertium-kaa$ git log -1
commit 54b29b3c1040fb45ead0155daa5ca3487ac934b5 (HEAD -> master, origin/master, origin/HEAD)
Author: Ilnar Salimzianov <ilnar@selimcan.org>
Date:   Sun Apr 7 01:15:30 2019 +0300

    add .travis.yml and test.py

apertium-kaa$ aq-covtest ../../../data4apertium/corpora/jam/kaa.txt kaa.automorf.bin 
Number of tokenised words in the corpus: 489
Coverage: 69.53%
Top unknown words in the corpus:
17	 Ayg
13	 l
13	 k
7	 j
5	 h
4	 redi
4	 ı
4	 shigi
3	 lken
3	 K
3	 ldi
3	 pıshı
2	 andı
2	 zir
2	 shik
2	 Yaq
2	 yde
2	 n
2	 m
2	 qayerge
Translation time: 0.016431331634521484 seconds
apertium-kaa$ 
```

## Coverage on the story after sharapat's changes:

```
apertium-kaa$ git log -1
commit e7429c8f63c9cdb443ee0ffc0f8d897a64f47209 (HEAD -> coding-challenge, origin/coding-challenge)
Author: sharapat <kalabaevshj@gmail.com>
Date:   Wed Apr 24 00:26:03 2019 +0500

    changed sh -> ch where neccessary

apertium-kaa$ aq-covtest ~/1Working/1Taruen/apertiumpp/data4apertium/corpora/jam/kaa.txt kaa.automorf.bin 
Number of tokenised words in the corpus: 413
Coverage: 87.89%
Top unknown words in the corpus:
4	 kóredi
3	 júda
3	 Aygúldiń
3	 pıshıǵı
2	 oynaǵandı
2	 Yaq
2	 úyde
2	 qayerge
1	 barqulla
1	 úydiń
1	 aldındaǵı
1	 oynaǵanına
1	 baratır
1	 Aygúlden
1	 kózlerin
1	 kórip
1	 turǵanı
1	 bolǵannan
1	 atirapına
1	 kórdińizbe
Translation time: 0.019109010696411133 seconds
```
Unsurprisingly, the coverage has increased, which is a good thing.

@sharapat , this is how you can install aq-covtest:  https://gist.github.com/IlnarSelimcan/87efbbe8a569833e68e89b126836e2bc . It is a tool for measuring the coverage of a transducers, i.e. what percentage of words in a corpus it recognizes.

As the next step, please check whether the *stems* of unknown words are in the `apertium-kaa.kaa.lexc`. In other words, make sure that `kór:kór V-TV ;` is there, and `Aygúl:Aygúl NP-ANT-F ;` is, etc.

If all stems from the story are already in the lexicon, it'll be easier for @jonorthwash to work on twol rules, since he'll know that unknown words aq-covtest returns from the story are unknown because of issues with twol, and not because their stems are not in `apertium-kaa.kaa.lexc`.

2019-04-24 21:01 UTC, IlnarSelimcan requested changes
@sharapat See inline comments .

.hfst files are binary files you get after compiling apertium-kaa. There's no need for tracking them in the repo. Please add the names of those files to `.gitignore` and remove them from the repo with `git rm`. If you know how to remove from the git history as well, please do so too :)

2019-04-24 21:01 UTC, IlnarSelimcan commented on apertium-kaa.kaa.lexc
> +JIó.:JIó ABBR ; ! "GDP"
`ó` should be capital letter.

2019-04-24 21:01 UTC, IlnarSelimcan commented on apertium-kaa.kaa.lexc
> +áwezov:áwezov NP-COG-OV ; ! ""
`á` should be capital.

2019-04-24 21:01 UTC, IlnarSelimcan commented on apertium-kaa.kaa.lexc
> +ótepov:ótepov NP-COG-OV ; ! ""
capital

2019-04-24 21:01 UTC, IlnarSelimcan commented on apertium-kaa.kaa.lexc
> +ábdiraxman:ábdiraxman NP-ANT-M ; ! "Äbdiraxman" (Arabic)
All names below should start with capital letter.

2019-04-24 21:01 UTC, IlnarSelimcan commented on apertium-kaa.kaa.lexc
> +ázerbayjan:ázerbayjan NP-TOP ; ! ""
capital

2019-04-24 21:01 UTC, IlnarSelimcan commented on apertium-kaa.kaa.lexc
> +ózbekstan:ózbekstan NP-TOP ; ! ""
capital

2019-04-30 19:51 UTC, IlnarSelimcan commented
This is just for future reference:

## Coverage on New Testament (which is written in the older latin alphabet) before updating `kaa.lexc` to new alphabet:

```
apertium-kaa$ aq-covtest ../../../data4apertium/corpora/bible/kaa@latn.gospelgo.txt kaa.automorf.bin                                                                                         
Number of tokenised words in the corpus: 187417
Coverage: 87.89%
Top unknown words in the corpus:
835      a
616      an
520      Muxaddes
353      Masix
342      Menin
342      g
273      qa
260      atırg
199      Meni
183      Masixtın
178      ler
172      ın
166      ja
161      ha
161      Petr
159      Mag
148      Pavel
147      su
144      gu
143      mag
Translation time: 3.298170804977417 seconds
```

## Coverage on New Testament after updating `kaa.lexc`

```
apertium-kaa$ aq-covtest ~/1Working/1Taruen/apertiumpp/data4apertium/corpora/bible/kaa@latn.gospelgo.txt kaa.automorf.bin 
Number of tokenised words in the corpus: 245947
Coverage: 72.66%
Top unknown words in the corpus:
3464	 ha
2076	 m
1878	 ko
1568	 a
1102	 u
888	 ku
817	 Qudaydın
802	 so
781	 an
757	 z
733	 ju
679	 lar
668	 na
653	 ja
624	 gu
579	 tu
520	 Muxaddes
509	 su
504	 ler
501	 g
Translation time: 2.879375457763672 seconds
```

Coverage on NT should get up to 87.89% after kaa.twol is updated (and NT text is also updated and/or some compatibility mode added to `apertium-kaa`).

2019-04-30 19:57 UTC, IlnarSelimcan requested changes

2019-04-30 19:57 UTC, IlnarSelimcan commented on apertium-kaa.kaa.lexc
> +ózbekstan:ózbekistan NP-TOP ; ! "" ! Dir/LR ! Use/Sub
Capitaliza both ó.

2019-04-30 19:57 UTC, IlnarSelimcan commented on apertium-kaa.kaa.lexc
> +ábdiraman:ábdiraman NP-ANT-M ; ! ""
бас әріп

2019-04-30 19:57 UTC, IlnarSelimcan commented on apertium-kaa.kaa.lexc
> +ábil:ábil NP-ANT-M ; ! "Äbil" (Arabic)
4340-4347 жолдар: бас әріп

2019-04-30 19:57 UTC, IlnarSelimcan commented on apertium-kaa.kaa.lexc
> +ómir:ómir NP-ANT-M ; ! "Ömir" (Arabic)
бас әріп

2019-04-30 19:57 UTC, IlnarSelimcan commented on apertium-kaa.kaa.lexc
> +óndiris:óndiris NP-ANT-M ; ! "Öndiris" (Kazakh)
бас әріп

2019-04-30 19:57 UTC, IlnarSelimcan commented on apertium-kaa.kaa.lexc
> +cukerberg:cukerberg NP-COG-MF ; ! "Zuckerberg"
бас әріп

2019-04-30 19:57 UTC, IlnarSelimcan commented on apertium-kaa.kaa.lexc
> +ábdiraman:ábdiraman NP-ANT-M ; ! ""
бас әріп.

And that's it. Everything else looks fine to me.

2019-05-02 16:57 UTC, sharapat commented on apertium-kaa.kaa.lexc
> +ómir:ómir NP-ANT-M ; ! "Ömir" (Arabic)
Why ómir should start with capital letter?

2019-05-02 17:49 UTC, jonorthwash commented on apertium-kaa.kaa.lexc
> +ómir:ómir NP-ANT-M ; ! "Ömir" (Arabic)
This is the name Ómir, not the common noun ómir.

2019-05-02 20:35 UTC, sharapat commented
> ## Coverage on the [story](https://github.com/taruen/apertiumpp/blob/master/data4apertium/corpora/jam/kaa.txt) before @sharapat 's changes:
> ```
> apertium-kaa$ git log -1
> commit 54b29b3c1040fb45ead0155daa5ca3487ac934b5 (HEAD -> master, origin/master, origin/HEAD)
> Author: Ilnar Salimzianov <xxxxxxxxxxxxxx>
> Date:   Sun Apr 7 01:15:30 2019 +0300
> 
>     add .travis.yml and test.py
> 
> apertium-kaa$ aq-covtest ../../../data4apertium/corpora/jam/kaa.txt kaa.automorf.bin 
> Number of tokenised words in the corpus: 489
> Coverage: 69.53%
> Top unknown words in the corpus:
> 17	 Ayg
> 13	 l
> 13	 k
> 7	 j
> 5	 h
> 4	 redi
> 4	 ı
> 4	 shigi
> 3	 lken
> 3	 K
> 3	 ldi
> 3	 pıshı
> 2	 andı
> 2	 zir
> 2	 shik
> 2	 Yaq
> 2	 yde
> 2	 n
> 2	 m
> 2	 qayerge
> Translation time: 0.016431331634521484 seconds
> apertium-kaa$ 
> ```
> 
> ## Coverage on the story after sharapat's changes:
> ```
> apertium-kaa$ git log -1
> commit e7429c8f63c9cdb443ee0ffc0f8d897a64f47209 (HEAD -> coding-challenge, origin/coding-challenge)
> Author: sharapat <xxxxxxxxxxxxxxxxxxxxx>
> Date:   Wed Apr 24 00:26:03 2019 +0500
> 
>     changed sh -> ch where neccessary
> 
> apertium-kaa$ aq-covtest ~/1Working/1Taruen/apertiumpp/data4apertium/corpora/jam/kaa.txt kaa.automorf.bin 
> Number of tokenised words in the corpus: 413
> Coverage: 87.89%
> Top unknown words in the corpus:
> 4	 kóredi
> 3	 júda
> 3	 Aygúldiń
> 3	 pıshıǵı
> 2	 oynaǵandı
> 2	 Yaq
> 2	 úyde
> 2	 qayerge
> 1	 barqulla
> 1	 úydiń
> 1	 aldındaǵı
> 1	 oynaǵanına
> 1	 baratır
> 1	 Aygúlden
> 1	 kózlerin
> 1	 kórip
> 1	 turǵanı
> 1	 bolǵannan
> 1	 atirapına
> 1	 kórdińizbe
> Translation time: 0.019109010696411133 seconds
> ```
> 
> Unsurprisingly, the coverage has increased, which is a good thing.
> 
> @sharapat , this is how you can install aq-covtest: https://gist.github.com/IlnarSelimcan/87efbbe8a569833e68e89b126836e2bc . It is a tool for measuring the coverage of a transducer, i.e. it shows percentage of words in a corpus the transducer recognizes.
> 
> As the next step, please check whether the _stems_ of unknown words are in the `apertium-kaa.kaa.lexc`. In other words, make sure that `kór:kór V-TV ;` is there, and `Aygúl:Aygúl NP-ANT-F ;` is, etc.
> 
> If all stems from the story are already in the lexicon, it'll be easier for @jonorthwash to work on `apertium-kaa.kaa.twol` rules, since he'll know that unknown words `aq-covtest` returns from the story are unknown because of issues with twol, and _not_ because their stems are missing from `apertium-kaa.kaa.lexc`.
> 
> @sharapat , also, we'll need some more texts written in (or converted to) the new orthography (for testing purposes).
> 
> These can be Karakalpak texts which you'd like to see translated to Uzbek (personal interest in translations is a good motivator). Any text works, but ideally they should be under a free license (public domain, creative commons-by, creative-commons-by-sa).

Addede the unknown words in apertium-kaa.kaa.lexc. Also edited atirapına to átirapına in [https://github.com/sharapat/story-translation-uzb-kaa-for-apertium/blob/master/kaa.txt](url), there was a mistake.

2019-05-07 18:48 UTC, merged